### ISSUE TITLE
Peer-to-Peer to Review

### ISSUE THREAD

**Issue by anita00001** [AbdusSattar-70/Leaderboard#3]
## Highlights
- Descriptive Pull Request

## Suggestions

- [ ] The score field is of `type text`, which may allow to add a string as well. Only a number is expected in the score field.
![image](https://user-images.githubusercontent.com/24216198/224925444-151972b2-b12d-401f-9714-9678a9766ede.png)

- [ ] The event listener for input is a form, I recommend you to listen to a `click` event to the `Submit` Button.
![image](https://user-images.githubusercontent.com/24216198/224926247-d399743c-b025-491f-81f7-64c306acdbb3.png)

**Comment by AbdusSattar-70** [comment]
Hello @anita00001, 
Thanks for your valuable suggestion and for investing time in my repo. I have modified the input attribute number instead of the text.
when I use the `click` listener instead of `submit` it throws an error from the API. It would be better to use `submit` in this context.
