### ISSUE TITLE
Peer to peer code review 

### ISSUE THREAD

**Issue by saluumaa** [AbdusSattar-70/Leaderboard#4]
### Highlights

Hello, @AbdusSattar-70, well done but there are some issues that you need to fix.

1. the score field is of type text, which may allow the addition of a string as well. Only a number is expected in the score field
https://user-images.githubusercontent.com/24216198/224926247-d399743c-b025-491f-81f7-64c306acdbb3.png)
3. the event listener for input is a form, I recommend you to listen to a **click** event to the **submit** button.
https://user-images.githubusercontent.com/24216198/224925444-151972b2-b12d-401f-9714-9678a9766ede.png)

**Comment by AbdusSattar-70** [comment]
### Hello @saluumaa,

### Thanks for reviewing - I have resolved it #6
